Q-1. Imagine you have a dataset where you have different Instagram features
like u sername , Caption , Hashtag , Followers , Time_Since_posted , and likes , now your task is
to predict the number of likes and Time Since posted and the rest of the features are
your input features. Now you have to build a model which can predict the
number of likes and Time Since posted.
Dataset This is the Dataset You can use this dataset for this question.

In [1]:
import pandas as pd

In [2]:
df=pd.read_csv("instagram_reach.csv")


In [3]:
df

Unnamed: 0  S.No              USERNAME  \
0            0     1         mikequindazzi   
1            1     2       drgorillapaints   
2            2     3    aitrading_official   
3            3     4  opensourcedworkplace   
4            4     5           crea.vision   
..         ...   ...                   ...   
95           8    19        michaelgarza__   
96           9    21           dvlp_search   
97          10    22            ecom.space   
98          11    24        lb3enterprises   
99          12    25          palmariusdev   

                                              Caption  Followers  \
0   Who are #DataScientist and what do they do? >>...       1600   
1   We all know where it’s going. We just have to ...        880   
2   Alexander Barinov: 4 years as CFO in multinati...        255   
3                                                sfad        340   
4   Ever missed a call while your phone was chargi...        304   
..                                                ...        ...   
95  328 S. Wetherly Drive, Beverly Hills, CA 90212...        614   
96  Credit @tristankappel To find more dvlp follow...        450   
97  We are coming up with the Best 21 Books that w...        182   
98  We’re only paid to move dirt once. It’s not ju...       2039   
99                    Obtén tu tienda en línea ahora.        741   

                                             Hashtags Time since posted  Likes  
0   #MachineLearning #AI #DataAnalytics #DataScien...          11 hours    139  
1    #deck .#mac #macintosh#sayhello #apple #steve...           2 hours     23  
2   #whoiswho #aitrading #ai #aitradingteam#instat...           2 hours     25  
3   #iot #cre#workplace #CDO #bigdata #technology#...           3 hours     49  
4   #instamachinelearning #instabigdata#instamarke...           3 hours     30  
..                                                ...               ...    ...  
95  #beverlyhills #realestate#losangelesrealestate...           3 hours     31  
96  #workspace #work #developer#development #devel...           3 hours     42  
97  #books #book #motivation #inspiration #life#bo...           3 hours     10  
98  #heavyequipment #underconstruction#dozer #real...           3 hours    222  
99  #marketing #programming#development #desarroll...           3 hours    109  

[100 rows x 8 columns]

In [4]:
df.shape

(100, 8)

In [5]:
df_new=df.copy()

In [6]:
df_new.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype 
---  ------             --------------  ----- 
 0   Unnamed: 0         100 non-null    int64 
 1   S.No               100 non-null    int64 
 2   USERNAME           100 non-null    object
 3   Caption            94 non-null     object
 4   Followers          100 non-null    int64 
 5   Hashtags           100 non-null    object
 6   Time since posted  100 non-null    object
 7   Likes              100 non-null    int64 
dtypes: int64(4), object(4)
memory usage: 6.4+ KB


In [7]:
df_new.describe().T

count    mean          std   min     25%    50%      75%     max
Unnamed: 0  100.0    8.94     6.639064   0.0    4.00    8.0    12.25    26.0
S.No        100.0   16.24     7.384286   1.0   10.75   16.5    22.25    30.0
Followers   100.0  961.96  1014.625670  11.0  252.75  612.0  1197.00  4496.0
Likes       100.0   46.48    55.086980   8.0   19.00   29.0    46.00   349.0

In [8]:
df_new.isnull().sum()

Unnamed: 0           0
S.No                 0
USERNAME             0
Caption              6
Followers            0
Hashtags             0
Time since posted    0
Likes                0
dtype: int64

In [9]:
df_new.duplicated().sum()

0

In [10]:
df_new

Unnamed: 0  S.No              USERNAME  \
0            0     1         mikequindazzi   
1            1     2       drgorillapaints   
2            2     3    aitrading_official   
3            3     4  opensourcedworkplace   
4            4     5           crea.vision   
..         ...   ...                   ...   
95           8    19        michaelgarza__   
96           9    21           dvlp_search   
97          10    22            ecom.space   
98          11    24        lb3enterprises   
99          12    25          palmariusdev   

                                              Caption  Followers  \
0   Who are #DataScientist and what do they do? >>...       1600   
1   We all know where it’s going. We just have to ...        880   
2   Alexander Barinov: 4 years as CFO in multinati...        255   
3                                                sfad        340   
4   Ever missed a call while your phone was chargi...        304   
..                                                ...        ...   
95  328 S. Wetherly Drive, Beverly Hills, CA 90212...        614   
96  Credit @tristankappel To find more dvlp follow...        450   
97  We are coming up with the Best 21 Books that w...        182   
98  We’re only paid to move dirt once. It’s not ju...       2039   
99                    Obtén tu tienda en línea ahora.        741   

                                             Hashtags Time since posted  Likes  
0   #MachineLearning #AI #DataAnalytics #DataScien...          11 hours    139  
1    #deck .#mac #macintosh#sayhello #apple #steve...           2 hours     23  
2   #whoiswho #aitrading #ai #aitradingteam#instat...           2 hours     25  
3   #iot #cre#workplace #CDO #bigdata #technology#...           3 hours     49  
4   #instamachinelearning #instabigdata#instamarke...           3 hours     30  
..                                                ...               ...    ...  
95  #beverlyhills #realestate#losangelesrealestate...           3 hours     31  
96  #workspace #work #developer#development #devel...           3 hours     42  
97  #books #book #motivation #inspiration #life#bo...           3 hours     10  
98  #heavyequipment #underconstruction#dozer #real...           3 hours    222  
99  #marketing #programming#development #desarroll...           3 hours    109  

[100 rows x 8 columns]

In [11]:
df_new.columns

Index(['Unnamed: 0', 'S.No', 'USERNAME', 'Caption', 'Followers', 'Hashtags',
       'Time since posted', 'Likes'],
      dtype='object')

In [12]:
df_new["Unnamed: 0"].unique()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26], dtype=int64)

In [13]:
df_new['S.No'].unique()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 13, 14, 15, 18, 20, 21,
       22, 23, 24, 26, 25, 27, 28, 29, 30, 12, 17, 16, 19], dtype=int64)

In [14]:
df_new['USERNAME'].unique()

array(['mikequindazzi', 'drgorillapaints', 'aitrading_official',
       'opensourcedworkplace', 'crea.vision', 'be.masterly',
       'lenovoworkstations', 'kirellb', 'ethicsandai',
       'diworksolucionesdeti', 'databowl', 'edwisor_india', 'ubiqum',
       'artificialintelligence.a.i', 'ansonmccade', 'jennifercodes',
       'eligible.api', 'ale_borba', 'amjstaffing', 'writtorg',
       'superdatascience', 'xotivtechnologies', 'onthetopsearch',
       'data_enthusiast', 'programmer.io', 'coding.is.life', 'theminest_',
       'philosophercoin', 'greenhousegroup', 'neondistrictrpg',
       'blocsidesports', 'cryptocrackhead', 'gsmusicgroupllc',
       'iotatokennews', 'bitpainting', '_linda_smith567', 'litebit.eu',
       'meganbloemsma', 'ricmiqads', 'hollympeck', 'artificial_quotes',
       'interwall', 'entrancegmbh', 'usccareercenter', '_ehab.othman_',
       'anki7singh', 'mbnsolutions', 'triatebr', 'orcan_intel',
       'funnelaico', 'iamalexleyva', 'astrokpj', 'big.data.hush',
   

In [15]:
df_new['Caption'].unique()

array(['Who are #DataScientist and what do they do? >> @MikeQuindazzi >> #MachineLearning #AI #DataAnalytics #DataScienc #DataLake >> https://buff.ly/2kYmF0s',
       'We all know where it’s going. We just have to\xa0#workresponsibly\xa0to postpone the date. This actually made into a business slide\xa0#deck\xa0.#mac\xa0#macintosh#sayhello\xa0#apple\xa0#stevejobs\xa0#ai\xa0#evolution#artificialintelligence\xa0#machinelearning#terminator\xa0#illbeback\xa0#technology#computerevolution\xa0#computerscience#sciencefiction#computersciencetosciencefiction#tomorrowstechnology\xa0#vr\xa0#ar\xa0#robot#robots\xa0#t2\xa0#businessdeck\xa0#businessslides#illustration\xa0#sketches\xa0#drawing',
       'Alexander Barinov: 4 years as CFO in multinationals, over 10 years of experience as financial advisory in Deloitte & EY, 6 of them as a partner. Focused on strategic management, finance, legal, and compliance. Worked for the global corporations including publicly traded companies. 5 years experience in 

In [16]:
df_new['Followers'].unique()

array([1600,  880,  255,  340,  304, 1231,  259, 1433,   13,  450,  149,
       2232, 1061,  533, 2904,  971,  285,  520,   75, 2691,  966,  334,
       1041, 4496,  166, 1211,  265, 1618,  279,  828,   12,  894,  610,
        226, 1168,  835,  124,  193,  258,  105,  273,  914,  118,  122,
       1180, 3139, 3725,  935, 1766, 2277,  348,   87, 2785, 3448,  530,
       3147,  918,  145,   11,  577,   66,   89, 2014,  151, 2175,  371,
       1003, 1200,  383,  955, 2372,  740, 2573,  181,  631,  246,  460,
        140,  888,  845,   91,  361, 2455,  262, 1158, 1196,  863,  106,
        179,   49,  614,  182, 2039,  741], dtype=int64)

In [17]:
df_new['Hashtags'].unique()

array(['#MachineLearning #AI #DataAnalytics #DataScienc #DataLake',
       '\xa0#deck\xa0.#mac\xa0#macintosh#sayhello\xa0#apple\xa0#stevejobs\xa0#ai\xa0#evolution#artificialintelligence\xa0#machinelearning#terminator\xa0#illbeback\xa0#technology#computerevolution\xa0#computerscience#sciencefiction#computersciencetosciencefiction#tomorrowstechnology\xa0#vr\xa0#ar\xa0#robot#robots\xa0#t2\xa0#businessdeck\xa0#businessslides#illustration\xa0#sketches\xa0#drawing',
       '#whoiswho\xa0#aitrading\xa0#ai\xa0#aitradingteam#instateam\xa0#instapeople\xa0#ai\xa0#trading#artificialintelligence\xa0#crypto#cryptocurrency\xa0#blockchain\xa0#tradingforex#forex\xa0#fiatmoney\xa0#coins\xa0#machinelearning#userexperience\xa0#instamachinelearning#instabigdata\xa0#instamarketing#artificialintelligence\xa0#deeplearning#datascience\xa0#industry\xa0#marketing#bigdata\xa0#datascience\xa0#machinelearning#ml',
       '#iot\xa0#cre#workplace\xa0#CDO\xa0#bigdata\xa0#technology#tech\xa0#work\xa0#computerscience\xa

In [18]:
df_new['Time since posted'].unique()

array(['11 hours', '2 hours', '3 hours', '4 hours', '7 hours', '8 hours',
       '9 hours', '5 hours', '20 hours', '14 hours', '24 hours'],
      dtype=object)

In [19]:
df_new['Likes'].unique()

array([139,  23,  25,  49,  30,  18,  35,  86,  22,  31,  48,  80,  94,
        28,  53,  29,  46,  34, 198,  19,  20,  11,  10, 148,  43,  37,
        90,  14, 273,  13,  93,  24, 136,   8,  41,  81,  16,  51, 157,
        17,  65, 349,  21,  27,  40,  50, 119,  55,  12,  33,   9,  32,
        42, 222, 109], dtype=int64)

In [20]:
df_new=df_new.drop("Unnamed: 0",axis= "columns")

In [21]:
df_new

S.No              USERNAME  \
0      1         mikequindazzi   
1      2       drgorillapaints   
2      3    aitrading_official   
3      4  opensourcedworkplace   
4      5           crea.vision   
..   ...                   ...   
95    19        michaelgarza__   
96    21           dvlp_search   
97    22            ecom.space   
98    24        lb3enterprises   
99    25          palmariusdev   

                                              Caption  Followers  \
0   Who are #DataScientist and what do they do? >>...       1600   
1   We all know where it’s going. We just have to ...        880   
2   Alexander Barinov: 4 years as CFO in multinati...        255   
3                                                sfad        340   
4   Ever missed a call while your phone was chargi...        304   
..                                                ...        ...   
95  328 S. Wetherly Drive, Beverly Hills, CA 90212...        614   
96  Credit @tristankappel To find more dvlp follow...        450   
97  We are coming up with the Best 21 Books that w...        182   
98  We’re only paid to move dirt once. It’s not ju...       2039   
99                    Obtén tu tienda en línea ahora.        741   

                                             Hashtags Time since posted  Likes  
0   #MachineLearning #AI #DataAnalytics #DataScien...          11 hours    139  
1    #deck .#mac #macintosh#sayhello #apple #steve...           2 hours     23  
2   #whoiswho #aitrading #ai #aitradingteam#instat...           2 hours     25  
3   #iot #cre#workplace #CDO #bigdata #technology#...           3 hours     49  
4   #instamachinelearning #instabigdata#instamarke...           3 hours     30  
..                                                ...               ...    ...  
95  #beverlyhills #realestate#losangelesrealestate...           3 hours     31  
96  #workspace #work #developer#development #devel...           3 hours     42  
97  #books #book #motivation #inspiration #life#bo...           3 hours     10  
98  #heavyequipment #underconstruction#dozer #real...           3 hours    222  
99  #marketing #programming#development #desarroll...           3 hours    109  

[100 rows x 7 columns]

In [22]:
df_new=df_new.drop("S.No",axis= "columns")

In [23]:
df_new

USERNAME                                            Caption  \
0          mikequindazzi  Who are #DataScientist and what do they do? >>...   
1        drgorillapaints  We all know where it’s going. We just have to ...   
2     aitrading_official  Alexander Barinov: 4 years as CFO in multinati...   
3   opensourcedworkplace                                               sfad   
4            crea.vision  Ever missed a call while your phone was chargi...   
..                   ...                                                ...   
95        michaelgarza__  328 S. Wetherly Drive, Beverly Hills, CA 90212...   
96           dvlp_search  Credit @tristankappel To find more dvlp follow...   
97            ecom.space  We are coming up with the Best 21 Books that w...   
98        lb3enterprises  We’re only paid to move dirt once. It’s not ju...   
99          palmariusdev                    Obtén tu tienda en línea ahora.   

    Followers                                           Hashtags  \
0        1600  #MachineLearning #AI #DataAnalytics #DataScien...   
1         880   #deck .#mac #macintosh#sayhello #apple #steve...   
2         255  #whoiswho #aitrading #ai #aitradingteam#instat...   
3         340  #iot #cre#workplace #CDO #bigdata #technology#...   
4         304  #instamachinelearning #instabigdata#instamarke...   
..        ...                                                ...   
95        614  #beverlyhills #realestate#losangelesrealestate...   
96        450  #workspace #work #developer#development #devel...   
97        182  #books #book #motivation #inspiration #life#bo...   
98       2039  #heavyequipment #underconstruction#dozer #real...   
99        741  #marketing #programming#development #desarroll...   

   Time since posted  Likes  
0           11 hours    139  
1            2 hours     23  
2            2 hours     25  
3            3 hours     49  
4            3 hours     30  
..               ...    ...  
95           3 hours     31  
96           3 hours     42  
97           3 hours     10  
98           3 hours    222  
99           3 hours    109  

[100 rows x 6 columns]

In [24]:
df_new=df_new.drop("Caption",axis= "columns")

In [25]:
df_new

USERNAME  Followers  \
0          mikequindazzi       1600   
1        drgorillapaints        880   
2     aitrading_official        255   
3   opensourcedworkplace        340   
4            crea.vision        304   
..                   ...        ...   
95        michaelgarza__        614   
96           dvlp_search        450   
97            ecom.space        182   
98        lb3enterprises       2039   
99          palmariusdev        741   

                                             Hashtags Time since posted  Likes  
0   #MachineLearning #AI #DataAnalytics #DataScien...          11 hours    139  
1    #deck .#mac #macintosh#sayhello #apple #steve...           2 hours     23  
2   #whoiswho #aitrading #ai #aitradingteam#instat...           2 hours     25  
3   #iot #cre#workplace #CDO #bigdata #technology#...           3 hours     49  
4   #instamachinelearning #instabigdata#instamarke...           3 hours     30  
..                                                ...               ...    ...  
95  #beverlyhills #realestate#losangelesrealestate...           3 hours     31  
96  #workspace #work #developer#development #devel...           3 hours     42  
97  #books #book #motivation #inspiration #life#bo...           3 hours     10  
98  #heavyequipment #underconstruction#dozer #real...           3 hours    222  
99  #marketing #programming#development #desarroll...           3 hours    109  

[100 rows x 5 columns]

In [26]:
df_new=df_new.drop("Hashtags",axis= "columns")

In [27]:
df_new

USERNAME  Followers Time since posted  Likes
0          mikequindazzi       1600          11 hours    139
1        drgorillapaints        880           2 hours     23
2     aitrading_official        255           2 hours     25
3   opensourcedworkplace        340           3 hours     49
4            crea.vision        304           3 hours     30
..                   ...        ...               ...    ...
95        michaelgarza__        614           3 hours     31
96           dvlp_search        450           3 hours     42
97            ecom.space        182           3 hours     10
98        lb3enterprises       2039           3 hours    222
99          palmariusdev        741           3 hours    109

[100 rows x 4 columns]

In [28]:
df_new.shape

(100, 4)

In [29]:
df_new.columns

Index(['USERNAME', 'Followers', 'Time since posted', 'Likes'], dtype='object')

In [30]:
df_new['Time since posted'].unique()

array(['11 hours', '2 hours', '3 hours', '4 hours', '7 hours', '8 hours',
       '9 hours', '5 hours', '20 hours', '14 hours', '24 hours'],
      dtype=object)

In [31]:
Time_since_posted_in_hours=[]

for i in df_new['Time since posted']:
    Time_since_posted_in_hours.append(i.replace('hours', ''))
se = pd.Series(Time_since_posted_in_hours)
df_new['Times since posted (hours)'] = se.values
df_new['Times since posted (hours)'] = pd.to_numeric(df_new['Times since posted (hours)'])
df_new = df_new.drop('Time since posted', axis=1)

In [32]:
df_new

USERNAME  Followers  Likes  Times since posted (hours)
0          mikequindazzi       1600    139                          11
1        drgorillapaints        880     23                           2
2     aitrading_official        255     25                           2
3   opensourcedworkplace        340     49                           3
4            crea.vision        304     30                           3
..                   ...        ...    ...                         ...
95        michaelgarza__        614     31                           3
96           dvlp_search        450     42                           3
97            ecom.space        182     10                           3
98        lb3enterprises       2039    222                           3
99          palmariusdev        741    109                           3

[100 rows x 4 columns]

In [33]:
from sklearn.preprocessing import LabelEncoder

In [34]:
username=LabelEncoder()

In [35]:
username.fit_transform(df["USERNAME"])

array([64, 29,  3, 71, 23, 14, 56, 54, 36, 28, 27, 32, 90, 12,  9, 52, 33,
        4,  6, 93, 84, 94, 70, 64, 26, 77, 22, 88, 75, 75, 39, 67, 19, 25,
       41, 50, 18,  1, 57, 64, 62, 80, 42, 11, 49, 34, 91,  0,  8, 60, 89,
       72, 71, 38, 43, 13, 16, 45, 51, 64, 81, 68, 24, 48,  5, 59, 87, 79,
       82, 40, 83, 61, 53, 17, 44, 78, 37, 58, 92,  7, 66,  2, 46, 10, 74,
       65, 35, 69, 20, 47, 86, 85, 21, 15, 76, 63, 30, 31, 55, 73])

In [36]:
df_new["USERNAME"]=username.fit_transform(df["USERNAME"])

In [37]:
df_new

USERNAME  Followers  Likes  Times since posted (hours)
0         64       1600    139                          11
1         29        880     23                           2
2          3        255     25                           2
3         71        340     49                           3
4         23        304     30                           3
..       ...        ...    ...                         ...
95        63        614     31                           3
96        30        450     42                           3
97        31        182     10                           3
98        55       2039    222                           3
99        73        741    109                           3

[100 rows x 4 columns]

In [38]:
df_new["Likes"].unique()

array([139,  23,  25,  49,  30,  18,  35,  86,  22,  31,  48,  80,  94,
        28,  53,  29,  46,  34, 198,  19,  20,  11,  10, 148,  43,  37,
        90,  14, 273,  13,  93,  24, 136,   8,  41,  81,  16,  51, 157,
        17,  65, 349,  21,  27,  40,  50, 119,  55,  12,  33,   9,  32,
        42, 222, 109], dtype=int64)

In [39]:
from sklearn.model_selection import train_test_split
X = df_new.drop(labels="Likes",axis=1)
y = df_new["Likes"]

In [40]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.33,random_state=42)

In [47]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error,r2_score

In [50]:
import numpy as np
lr = LinearRegression()
lr.fit(X_train,y_train)
y_pred = lr.predict(X_test)

mse = mean_squared_error(y_test,y_pred)
rmse = np.sqrt(mse)
r2 = r2_score(y_test, y_pred)

print("Mean Squared Error (MSE):", mse)
print("Root Mean Squared Error (RMSE):", rmse)
print("R-squared (R²):", r2)

Mean Squared Error (MSE): 1223.892809140281
Root Mean Squared Error (RMSE): 34.98417941213258
R-squared (R²): 0.6729120543825504
